### PR TITLE
Fixes and speed

### PR DESCRIPTION
**Pull request by kno10**
These patches optimize some parts of Batik, largely by replacing outdated classes (e.g. Batik `HashTable`) with faster JDK classes (e.g. `HashMap`) that maybe didn't exist yet at the time that code was written. In some cases, this also now uses Generics, rather than casts.

In particular, I also optimized the EventListener code.

The patch also avoids calling "String.intern" on a string that frequently will be already our known constant; in particular when cloning or importing subtrees, e.g., when handling `<svg:use>`.

`namespaceURI == SVG_NAMESPACE_URI ? SVG_NAMESPACE_URI : namespaceURI.intern()`

is trivial, but makes a noticeable difference for me, as it avoids a very common roundtrip through a large hashmap (although in hotspot itself, so you don't easily see this in the profiler).

### CODE REVIEW

**Comment by simonsteiner1984** [comment]
See BATIK-1204

**Comment by kno10** [comment]
@simonsteiner1984 for the hash table, I also had added generics, which makes the code simpler in many cases because you can remove casts.
For performance, the other fixes are even more important. The `String.intern()` roundtrip seems to be noticeable. And in particular when cloning subtrees (e.g. `<svg:use>`) we do know they are already interned, and usually our known constant SVG namespace string. Event handling can be simplified a lot, too.

**Comment by simonsteiner1984** [comment]
I need to apply the rest of your changes at some point, I was just doing the simple change of remove hashtable first

**Comment by simonsteiner1984** [comment]
It would be better if you could add replication steps for a performance issue to we can verify fix

**Comment by simonsteiner1984** [comment]
The imageio issue should be seperate from this bug with replication steps

**Comment by kno10** [comment]
I didn't see any obvious way of scripted performance benchmarking with Batik, sorry.
Yes, my branch has two purposes `fixesSpeed` patches. As they are separate commits, they are trivial to cherry pick, and I don't see much use in breaking them into separate branches just because. There already is a separate issue for the register() bug, and whether or not to allow the additional codecs is largely a matter of whether they are still available in the JDK. I didn't check if any of them got eventually removed in Java 8 or 9. With Java 7+ the newer (and higher-priority) codecs should be used anyway. But unfortunately, one of the Maven central packages had been built with Java 6, and thus could not compile these codecs, and then the fallback codecs were not enabled either - worst combination. The registry is supposed to allow multiple codecs for the same file type, with priorities (but as mentioned, adding a higher-priority codec later on does not work, because it does not invalidate the registry cache correctly).

**Pull request closed without merging**
